server:

spring:
  data:
    mongodb:
      uri: mongodb://test:123456@steamhy.com:27017/test



#noSslPort: 81
payjs:
  mchid: 1547187151
  key: LfFjXZ6ANijkPSEC
  url: https://payjs.cn/api/native
  notifyUrl: https://steamhy.com:8082/payHandle
