server:

spring:
  data:
    mongodb:
      uri: mongodb://localhost:28017/test


#noSslPort: 81
payjs:
  mchid: 1547187151
  key: LfFjXZ6ANijkPSEC
  url: https://payjs.cn/api/native
  notifyUrl: https://steamhy.com:${server.port}/payHandle
