server:
  port: 8080

spring:
  application:
    name: activity
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myadmin?characterEncoding=UTF-8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      filters: stat
  data:
    mongodb:
      uri: mongodb://localhost:27017/test


  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    jedis:
      pool:
        max-idle: 20
        min-idle: 0
        max-active: 8

  #扫描xml
mybatis:
  mapper-locations: classpath*:/mappers/*.xml
  #开启驼峰命名转换
  configuration.map-underscore-to-camel-case: true

logging:
  level.com.chs.activity.dao: debug



