server:
  ssl:
    key-store: classpath:5467488_steamhy.com.pfx
    key-store-type: PKCS12
    key-store-password: F47OXM13

spring:
  data:
    mongodb:
      uri: mongodb://localhost:28017/test


noSslPort: 80
payjs:
  mchid: 1547187151
  key: LfFjXZ6ANijkPSEC
  url: https://payjs.cn/api/native
  notifyUrl: https://steamhy.com:${server.port}/payHandle
