spring:
  datasource:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/myadmin?characterEncoding=UTF-8
      username: root
      password: 123456

      type: com.alibaba.druid.pool.DruidDataSource

      druid:
        filters: stat
  jackson:
    time-zone: GMT+8

  redis:
      host: 127.0.0.1
      port: 6379
  jpa:
      hibernate:
        ddl-auto: update
      show-sql: true

#扫描xml
mybatis:
  mapper-locations: classpath*:/mappers/*.xml
  #别名
  type-aliases-package: com.web.entity
  #开启驼峰命名转换
  configuration:
    map-underscore-to-camel-case: true


pagehelper:
  helperDialect: mysql

logging:
  level:
    com.chs.dao: debug

uploadRootPath: d:/upload/