server:
  port: 8081

spring:
  application:
    name: order

eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:123456@localhost:8761/eureka/

    registerWithEureka: true
    fetchRegistry: true