server:
  port: 8086

spring:
  application:
    name: user

eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:123456@localhost:8761/eureka/

    registerWithEureka: true
    fetchRegistry: true